version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase....
      - mvn clean package
  post_build:
    commands:
      - echo Build completed succesfully
artifacts:
  files:
    - target/process-office-files.jar
  discard-paths: yes