springdoc:  api-docs:    path: /api-docsendpoints:  api-contrato: http://appjurisprudenciaservice-env.eba-rhrm7mpk.us-east-2.elasticbeanstalk.com/api-contrato/logging:  file:    path: /var/log/tomcat/spring.log
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
aws:
  config:
    region: us-east-2
    access-key: AKIA5Z6LZFXPAWUQ2LFZ
    secret-key: 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
    service-endpoint: dynamodb.us-east-2.amazonaws.com
        